### ISSUE TITLE
No Save Data Found for Lego Star Wars: The Video Game

### ISSUE THREAD

**Issue by hrjs84** [mtkennerly/ludusavi-playnite#65]
I have the game installed to an external drive D:\Games\Lego Star Wars. The current manifest entry is 
```
"Lego Star Wars: The Video Game":
  files:
    "<base>/SWLEGO.BIN":
      tags:
        - config
      when:
        - os: windows
    "<base>/lsw_*":
      tags:
        - save
      when:
        - os: windows
```
My save path matches this, in D:\Games\Lego Star Wars\lsw_0. However, running the backup says `No save data found to back up for Lego Star Wars: The Video Game` I am on Ludsavi v0.21.0

Edit: I can get it to work with a custom game entry, but I would really like to get this working properly for the future
